blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # Blog creation
    path('create/', views.create, name='create'),
    path('write/<int:id>', views.write, name='write'),

    # Blog labeling
    path('write/<int:id>/create-area-label', views.create_area_label, name='create_area_label'),
    path('write/<int:id>/delete-area-label/<int:area_id>', views.delete_area_label, name='delete_area_label'),
    path('write/<int:id>/create-activity-label', views.create_activity_label, name='create_activity_label'),
    path('write/<int:id>/delete-activity-label/<int:activity_id>', views.delete_activity_label, name='delete_activity_label'),

    # Blog content editing
    path('section/delete/<int:section_id>', views.delete_blog_section, name='delete_section'),
    path('publish/<int:blog_id>', views.publish_blog, name='publish_blog'),
    path('unpublish/<int:blog_id>', views.unpublish_blog, name='unpublish_blog'),

    # Blog read
    path('<int:blog_id>', views.detail, name='detail_blog'),
    path('list/', views.blog_list, name='blog_list'),

    # Blog comments
    path('create-comment/<int:blog_id>', views.create_comment),
    path('reply-comment/<int:comment_id>', views.reply_comment),
    path('edit-comment/<int:comment_id>', views.edit_comment),
    path('delete-comment/<int:comment_id>', views.delete_comment),

    # Blog reports
    path('report/<int:blog_id>', views.report)
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about-us', views.about, name='about'),
    path('filter-search', views.filter_search, name='filter_search'),
    path('search-result', views.search_result, name='search_result')
]

petualanganku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('labels/', include('labels.urls')),
    path('', include('home.urls')),
    path('manage-report/', include('manage_report.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.http.response import HttpResponse
from blog.models import Blog, Area
from labels.models import ActivityLabel
from django.db.models import Q
from django.shortcuts import render
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
# Create your views here.

def home(request):
    context = {'list_blog_all': Blog.objects.filter(is_published=True).all()}
    return render(request, "home/index.html", context=context)

def about(request):
    return render(request, "home/about_us.html")

def filter_search(request):
    list_act_all = ActivityLabel.objects.all()
    context = {'list_act_all': list_act_all}
    return render(request, "home/filter_search.html", context=context)

def search_result(request):
    if request.method == "POST":
        if request.POST.get('keyword-search'):
            keyword = request.POST.get('keyword-search')
            keyword_lookup = Q(title__icontains=keyword) & Q(is_published=True)
            
            full_lookup = keyword_lookup

            if request.POST.getlist('filter-area'):
                filter_area_lookup = None
                filter_area = request.POST.getlist('filter-area')

                for i in filter_area:
                    area = i.split(', ')
                    if i == filter_area[0]:

                        filter_area_lookup = Q(
                            blog_area_label__province=area[0],
                            blog_area_label__city=area[1],
                            )

                    else:
                        filter_area_lookup |= Q(
                            blog_area_label__province=area[0],
                            blog_area_label__city=area[1],
                            )
                if filter_area_lookup:
                    full_lookup &= filter_area_lookup
            
            if request.POST.getlist('filter-activity'):
                filter_activity_lookup = None
                filter_activity = request.POST.getlist('filter_activity')

                for i in filter_activity:
                    if i == filter_activity[0]:

                        filter_activity_lookup = Q(
                            activity_labels__name=i,
                            )

                    else:
                        filter_activity_lookup |= Q(
                            activity_labels__name=i,
                            )

                if filter_activity_lookup:
                    full_lookup &= filter_activity_lookup

            search_result = Blog.objects.filter(full_lookup)
            context = {'blogs' : search_result}
        else:
            return HttpResponse('Please enter keyword for search.')
    return render(request, "home/search_result.html", context)

home/templates/home/about_us.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Homepage{% endblock title %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'home/about_us.css' %}" type="text/css">
{% endblock head %}

{% block body %}
{% include 'navbar.html' %}
<div class="main-container">
    <div class="submain-container">
        <div class='sub-container'>
            <img class="girlc" src="{% static 'img\girlc.svg'%}" alt="">
        </div>
        
        <div class="sub-container">
            <div class="sub-container-msg">
                <p class="title-page">About Us</p>
                <p class="desc-page"><span class="imp-word">Petualanganku</span> is a Blog app that let users share their travelling experiences in Indonesia.</p>
                <p class="desc-page"><span class="imp-word">(Made by C-15).</span></p>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% endblock script %}

home/templates/home/filter_search.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Filter Search{% endblock title %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'home/filter_search.css' %}" type="text/css">
{% endblock head %}
{% block body %}
{% include 'navbar.html' %}
<div class="main-container">
    <div class='sub-container info'>
        <p class="title-page">Filter Search</p>
        <p class="desc-page">You can find searchable blogs in this web with extra additional help, <span class="imp-word">filters!</span> Through <span class="imp-word">activity and area filters</span>, you can find specific blogs that you wish 😊</p>
    </div>
    
    <div class="sub-container main-form-search">
        <form class="filter-search" id="filter-search-form" action="{% url 'home:search_result' %}" method="post">{% csrf_token %}</form>
        
        <div class="sub-form-search keyword-input">
            <p class="title-form">Keyword</p>
            <input class="keyword-search" type="text" name="keyword-search" form="filter-search-form" required>
        </div>
        
        <div class="sub-container-form activity-label">
            <p class="title-form">Activity Filter</p>
            <div class="activity-list">
                <select name="activity-label-list" id="activity-label-list">
                    <option value="-" disabled selected>-</option>
                    {% for act in list_act_all %}
                        <option value="{{act.id}}-{{act.name}}">{{act.name}}</option>
                    {% endfor %}
                </select>
                <input class="pick-label activity" type="button" value="+">
            </div>

            <div class="activity-label-input">
                
                <div class="activity-selected">
                    <ul class="list-label" id="list-act-picked">
                    </ul>
                </div>
            </div>
            
        </div>
        
        <div class="sub-container-form area-label">
            <p class="title-form">Area Filter</p>
            <div class="area-list">
                <div class="province-input">
                    <p class="subtitle-form"><span class="imp-word">Province</span></p>
                    <select name="province" id="province-list" class="item-province">
                        <option value="-" disabled selected>-</option>
                    </select>
                </div>          
                
                <div class="city-input">
                    <p class="subtitle-form"><span class="imp-word">City</span></p>
                    <select name="city" id="city-list" class="item-city">
                        <option value="-" disabled selected>-</option>
                    </select>
                </div>
                <input class="pick-label area" type="button" value="+">
            </div>

            <div class="area-label-input">
                <div class="area-selected">
                    <ul class="list-label" id="list-area-picked">

                    </ul>

                </div>
            </div> 

        </div>
        
        <input class="submit-search" type="submit" value="Search" form="filter-search-form">


    </div>
</div>
{% endblock body %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="{% static 'home/filter_search.js' %}"></script>
{% endblock script %}

home/templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Homepage{% endblock title %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'home/index.css' %}" type="text/css">
{% endblock head %}

{% block body %}
{% include 'navbar.html' %}
<div class="main-container">
    <div class='sub-container info'>
        <img src="{% static 'img\bag.svg'%}" alt="">
    {% if not list_blog_all %}
        <div class="sub-container-msg">
            <p class="title-page">Home</p>
            <p class="desc-page">No blogs can be found :(</p>
        </div>
    {% else %}
        <div class="sub-container-msg">
            <p class="title-page">Home</p>
            <p class="desc-page">Find numerous blog about travelling in Indonesia!</p>
        </div>
    </div>
    
    
    <div class="sub-container list-blog">
        {% for blog in list_blog_all %}
        
        <div class="card-blog">
            <a class="blog-details" href="{% url 'blog:detail_blog' blog.id %}">
                <span class="link-spanner"></span>
            </a>
            <div class="thumbnail-card-blog">
                {% if blog.thumbnail %}
                <img src="{{blog.thumbnail.url}}" class="thumb">
                {% else %}
                <img src="{% static 'img\issue-placeholder-thumbnail.jpg' %}" class="thumb">
                {% endif %}
            </div>
            <div class="info-card-blog">
                <div class="author-info">
                    <div class="author-pp">
                        <img src="{% static 'img\PP-Placeholder.svg' %}" alt="">
                    </div>
                    <p>{{blog.author}}</p>
                </div>
                <div class="blog-info">
                    <p class="blog-title">{{blog.title|safe}}</p>
                    <div class="blog-labels">
                        <ul class="list-label">
                            {% for ar in blog.blog_area_label.all %}
                            <li class="label-item">{{ ar.getLabel }}</li>
                            {% endfor %}

                            {% for ac in blog.activity_labels.all %}
                            <li class="label-item">{{ ac.name }}</li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="blog-numbers">
                        <div class="blog-n comment">
                            <img src="{% static 'img\comment.svg' %}"" alt="">
                            <p>{{blog.comments.all|length}}</p>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>
        
        {% endfor %}
        
    </div>
    {% endif %}
</div>
{% endblock body %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% endblock script %}

home/templates/home/search_result.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Filter Search{% endblock title %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'home/search_result.css' %}" type="text/css">
{% endblock head %}
{% block body %}
{% include 'navbar.html' %}
<div class="main-container">
    <div class='sub-container info'>
        <p class="title-page">Search Result</p>
    {% if not blogs %}
        <div class="sub-container-msg">
            <p class="desc-page">No blogs can be found, try another search!</p>
            <a href="{% url 'home:filter_search' %}"><button class="search-again">Search again</button></a>
        </div>
    {% else %}
        <div class="sub-container-msg">
            <p class="desc-page">Here is/are the search result based on your preferences!</p>
        </div>
    </div>
    
    
    <div class="sub-container search-result">
        {% for blog in blogs %}
        
        <div class="card-blog">
            <a class="blog-details" href="{% url 'blog:detail_blog' blog.id %}">
                <span class="link-spanner"></span>
            </a>
            <div class="thumbnail-card-blog">
                {% if blog.thumbnail %}
                <img src="{{blog.thumbnail.url}}" class="thumb">
                {% else %}
                <img src="{% static 'img\issue-placeholder-thumbnail.jpg' %}" class="thumb">
                {% endif %}
            </div>
            <div class="info-card-blog">
                <div class="author-info">
                    <div class="author-pp">
                        <img src="{% static 'img\PP-Placeholder.svg' %}" alt="">
                    </div>
                    <p>{{blog.author}}</p>
                </div>
                <div class="blog-info">
                    <p class="blog-title">{{blog.title}}</p>
                    <div class="blog-labels">
                        <ul class="list-label">
                            {% for ar in blog.blog_area_label.all %}
                            <li class="label-item">{{ ar.getLabel }}</li>
                            {% endfor %}

                            {% for ac in blog.activity_labels.all %}
                            <li class="label-item">{{ ac.name }}</li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="blog-numbers">
                        <div class="blog-n comment">
                            <img src="{% static 'img\comment.svg' %}"" alt="">
                            <p>{{blog.comments.all|length}}</p>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>
        
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock body %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock script %}