blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # Blog creation
    path('create/', views.create, name='create'),
    path('write/<int:id>', views.write, name='write'),

    # Blog labeling
    path('write/<int:id>/create-area-label', views.create_area_label, name='create_area_label'),
    path('write/<int:id>/delete-area-label/<int:area_id>', views.delete_area_label, name='delete_area_label'),
    path('write/<int:id>/create-activity-label', views.create_activity_label, name='create_activity_label'),
    path('write/<int:id>/delete-activity-label/<int:activity_id>', views.delete_activity_label, name='delete_activity_label'),

    # Blog content editing
    path('section/delete/<int:section_id>', views.delete_blog_section, name='delete_section'),
    path('publish/<int:blog_id>', views.publish_blog, name='publish_blog'),
    path('unpublish/<int:blog_id>', views.unpublish_blog, name='unpublish_blog'),

    # Blog read
    path('<int:blog_id>', views.detail, name='detail_blog'),
    path('list/', views.blog_list, name='blog_list'),

    # Blog comments
    path('create-comment/<int:blog_id>', views.create_comment),
    path('reply-comment/<int:comment_id>', views.reply_comment),
    path('edit-comment/<int:comment_id>', views.edit_comment),
    path('delete-comment/<int:comment_id>', views.delete_comment),

    # Blog reports
    path('report/<int:blog_id>', views.report)
]

labels/urls.py
from django.urls import path
from . import views
app_name = 'labels'

urlpatterns = [
    path('', views.manage, name='manage'),
    path('add/', views.add, name='add'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
]

petualanganku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('labels/', include('labels.urls')),
    path('', include('home.urls')),
    path('manage-report/', include('manage_report.urls')),
]

labels/models.py
from django.db import models
from blog.models import Blog
# Create your models here.

class ActivityLabel(models.Model):
    name = models.TextField(blank=False, unique=True)
    blogs = models.ManyToManyField(Blog, related_name="activity_labels", blank=True)

labels/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import *

# Create your views here.
DUMMY = ["hiking", "swimming", "skiing", "surfing"]

def require_is_admin(view):
    ERRMSG = 'You must be an admin to view this page'
    def wrapper(*args, **kwargs):
        request = args[0]
        try:
            if not request.user.profile.is_admin:
                return HttpResponse(ERRMSG, status=401)
            else:
                return view(*args, **kwargs)
        except User.DoesNotExist:
            return HttpResponse(ERRMSG, status=401)
        except AttributeError:
            return HttpResponse(ERRMSG, status=401)            
    return wrapper

@require_is_admin
def manage(request):
    context = {'labels': [label.name for label in ActivityLabel.objects.all()]}
    return render(request, 'labels/manage.html', context)

@require_is_admin
def add(request):
    if request.method == 'POST':
        new_label_name = request.POST['label-name']
        if ActivityLabel.objects.filter(name=new_label_name).exists():
            messages.error(request, 'Label already exists')
        else:
            ActivityLabel(name=new_label_name).save()
            messages.success(request, 'Label added')
    context = {}
    return render(request, 'labels/add.html', context)

@require_is_admin
def edit(request):
    context = {}
    if request.method == 'POST':
        old_label_name = request.POST['label-name']
        new_label_name = request.POST['new-label-name']
        if ActivityLabel.objects.filter(name=old_label_name).exists():
            if ActivityLabel.objects.filter(name=new_label_name).exists():
                messages.error(request, f'Label "{new_label_name}" already exists')
                context['label_name'] = old_label_name
                context['new_label_name'] = new_label_name
            else:
                curr_label = ActivityLabel.objects.get(name=old_label_name)
                curr_label.name = new_label_name
                curr_label.save(force_update=True)
                messages.success(request, f'Label "{old_label_name}" changed to "{new_label_name}"')
        else:
            messages.error(request, f'Label "{old_label_name}" does not exist')
            context['label_name'] = old_label_name
            context['new_label_name'] = new_label_name
    return render(request, 'labels/edit.html', context)

@require_is_admin
def delete(request):
    if request.method == 'POST':
        label_name = request.POST['label-name']
        to_delete = ActivityLabel.objects.filter(name=label_name)
        if to_delete.exists():
            to_delete.delete()
            messages.success(request, 'Label deleted.')
        else:
            messages.error(request, 'Label does not exist')
    context = {}
    return render(request, 'labels/delete.html', context)

labels/templates/labels/add.html
{% extends 'labels/base.html' %}

{% block title %}Add label{% endblock title %}

{% block navigation %}
    <div class="nav-button"><a href='{% url 'labels:manage' %}'>Manage</a></div>
    <div class="nav-button"><a href='{% url 'labels:edit' %}'>Edit</a></div>
    <div class="nav-button"><a href='{% url 'labels:delete' %}'>Delete</a></div>   
{% endblock navigation %}

{% block content %}
   
    
    <form method="POST" action="{% url 'labels:add' %}" class="form">
        {% csrf_token %}
        <div class="form-field">Label name</div>
        <div class="form-group">
            <input name='label-name' type="text" placeholder="Insert label name..." required>
        </div>
        <div class="form-button">
            <input type="submit" value="Add">
        </div>
    </form>

{% endblock content %}

labels/templates/labels/base.html
{% extends 'base.html' %}

{% load static %}


{% block head %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'labels/styles.css' %}" type="text/css">


{% endblock head %}

{% block body %}

    {% include 'navbar.html' %}    
    <div class="messages">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %} class="message {{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}
    </div>
    <div class="navigation-parent">
    {% block navigation %}
    {% endblock navigation %}
    </div>
    <div class="content">
    {% block content %}
    {% endblock content %}
    </div>
{% endblock body %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% endblock script %}

labels/templates/labels/delete.html
{% extends 'labels/base.html' %}

{% block title %}Delete label{% endblock title %}

{% block navigation %}
    <div class="nav-button"><a href='{% url 'labels:add' %}'>Add</a></div>
    <div class="nav-button"><a href='{% url 'labels:edit' %}'>Edit</a></div>
    <div class="nav-button"><a href='{% url 'labels:manage' %}'>Manage</a></div>
{% endblock navigation %}

{% block content %}
    
    
    <form method="POST" action="{% url 'labels:delete' %}" class="form">
        {% csrf_token %}
        <div class="form-field">Label name</div>
        <div class="form-group">
            <input name='label-name' type="text" placeholder="Insert label name..." required>
        </div>
        <div class="form-button">
            <input type="submit" value="Delete">
        </div>
    </form>


{% endblock content %}

labels/templates/labels/edit.html
{% extends 'labels/base.html' %}

{% block title %}Edit label{% endblock title %}


{% block navigation %}
    <div class="nav-button"><a href='{% url 'labels:add' %}'>Add</a></div>
    <div class="nav-button"><a href='{% url 'labels:manage' %}'>Manage</a></div>
    <div class="nav-button"><a href='{% url 'labels:delete' %}'>Delete</a></div>
{% endblock navigation %}

{% block content %}

    <form method="POST" action="{% url 'labels:edit' %}" class="form">
        {% csrf_token %}
        <div class="form-field">Label name</div>
        <div class="form-group">
            <input name='label-name' type="text" placeholder="Insert label name..." value="{{ label_name }}" required>
        </div>
        <div class="form-field">New label name</div>
        <div class="form-group">
            <input name='new-label-name' type="text" placeholder="Insert new label name..." value="{{ new_label_name }}" required>
        </div>
        <div class="form-button">
            <input type="submit" value="Edit">
        </div>
    </form>

{% endblock content %}

labels/templates/labels/manage.html
{% extends 'labels/base.html' %}

{% block title %}Manage labels{% endblock title %}


{% block navigation %}
    <div class="nav-button"><a href='{% url 'labels:add' %}'>Add</a></div>
    <div class="nav-button"><a href='{% url 'labels:edit' %}'>Edit</a></div>
    <div class="nav-button"><a href='{% url 'labels:delete' %}'>Delete</a></div>
{% endblock navigation %}

{% block content %}

    <table class="labels-table">
        <thead>
            <tr>
                <th>Label Name</th>
            </tr>
        </thead>
        <tbody>
        {% for label in labels %}
            <tr class="table-row">
                <td> {{ label }} </td>
            </tr>
        {% endfor %}
        </tbody> 
        
    </table> 

{% endblock content %}