blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # Blog creation
    path('create/', views.create, name='create'),
    path('write/<int:id>', views.write, name='write'),

    # Blog labeling
    path('write/<int:id>/create-area-label', views.create_area_label, name='create_area_label'),
    path('write/<int:id>/delete-area-label/<int:area_id>', views.delete_area_label, name='delete_area_label'),
    path('write/<int:id>/create-activity-label', views.create_activity_label, name='create_activity_label'),
    path('write/<int:id>/delete-activity-label/<int:activity_id>', views.delete_activity_label, name='delete_activity_label'),

    # Blog content editing
    path('section/delete/<int:section_id>', views.delete_blog_section, name='delete_section'),
    path('publish/<int:blog_id>', views.publish_blog, name='publish_blog'),
    path('unpublish/<int:blog_id>', views.unpublish_blog, name='unpublish_blog'),

    # Blog read
    path('<int:blog_id>', views.detail, name='detail_blog'),
    path('list/', views.blog_list, name='blog_list'),

    # Blog comments
    path('create-comment/<int:blog_id>', views.create_comment),
    path('reply-comment/<int:comment_id>', views.reply_comment),
    path('edit-comment/<int:comment_id>', views.edit_comment),
    path('delete-comment/<int:comment_id>', views.delete_comment),

    # Blog reports
    path('report/<int:blog_id>', views.report)
]

petualanganku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('labels/', include('labels.urls')),
    path('', include('home.urls')),
    path('manage-report/', include('manage_report.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name='blogs')
    title = models.TextField(blank=True)
    thumbnail = models.ImageField(blank=True)
    is_published = models.BooleanField(blank=False, default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

class ContentSection(models.Model):
    blog = models.ForeignKey(Blog, blank=False, on_delete=models.CASCADE, related_name='sections')
    order = models.IntegerField()
    text_content = models.TextField(blank=True)
    image_content = models.ImageField(blank=True)
    caption_content = models.TextField(blank=True)
    
class Area(models.Model):
    province = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    blog_labeled = models.ForeignKey(Blog, related_name="blog_area_label", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "{}, {}".format(self.province, self.city)

    def getLabel(self):
        return "{}, {}".format(self.province, self.city)

class Comment(models.Model):
    commentator = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name="userComments")
    blog = models.ForeignKey(Blog, blank=False, on_delete=models.CASCADE, related_name="comments")
    replyTo = models.ForeignKey("Comment", blank=True, null=True, on_delete=models.CASCADE, related_name="repliesToThisComment")
    content = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now=True)

class Report(models.Model):
    blog = models.ForeignKey(Blog, blank=False, on_delete=models.CASCADE, related_name="report")
    reportType = models.TextField()
    reportDescription = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) 

blog/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.db.models import base, Prefetch
from django.shortcuts import render, get_object_or_404, redirect
from django.http import QueryDict, HttpResponseNotFound

import json

from .models import *
from labels.models import ActivityLabel
from .utils import decode_base64_file

# Create your views here.

@login_required
def create(request):
    blog = Blog.objects.create(author=request.user)
    return redirect('/blog/write/' + str(blog.id))

@login_required
@require_http_methods(['GET', 'POST'])
def write(request, id):
    blog = Blog.objects.filter(id=id).prefetch_related(Prefetch('sections', queryset=ContentSection.objects.order_by('order'))).get()

    if blog.author.username != request.user.username:
        return HttpResponse('You need to be the author to edit a blog')

    if request.method == 'GET':
        return render(request, 'blog/write_blog.html', context={'blog': blog})

    elif request.method == 'POST':
        blog.title = request.POST.get('title')

        if 'base64' in request.POST.get('thumbnail'):
            blog.thumbnail = decode_base64_file(request.POST.get('thumbnail'))

        blog.save()

        sections = json.loads(request.POST.get('sections'))

        # Update ContentSection
        for order in sections:
            section = sections[order]
            
            if section['type'] == 'text':
                if section['id'] == '0':
                    section_model = ContentSection(blog=blog, order=int(order), text_content=section['content'])
                    section_model.save()

                else:
                    ContentSection.objects.filter(id=int(section['id'])).update(order=int(order), text_content=section['content'])

            else:
                image = decode_base64_file(section['content'])

                if section['id'] == '0':
                    section_model = ContentSection(blog=blog, order=int(order), image_content=image, caption_content=section['caption'])
                    section_model.save()

                else:
                    ContentSection.objects.filter(id=int(section['id'])).update(order=int(order), caption_content=section['caption'])

        return HttpResponse('Success')

@login_required
@require_http_methods(['GET'])
def delete_blog_section(request, section_id):
    section = ContentSection.objects.filter(id=section_id).get()

    if section.blog.author.username == request.user.username:
        section.delete()

        return HttpResponse('Success')

@login_required
@require_http_methods(['GET'])
def publish_blog(request, blog_id):
    blog = Blog.objects.filter(id=blog_id).select_related('author').get()

    if blog.author.username == request.user.username:
        blog.is_published = True
        blog.save()

        return HttpResponse('Success')

@login_required
@require_http_methods(['GET'])
def unpublish_blog(request, blog_id):
    blog = Blog.objects.filter(id=blog_id).select_related('author').get()

    if blog.author.username == request.user.username:
        blog.is_published = False
        blog.save()

        return HttpResponse('Success')

@login_required
@require_http_methods(['GET'])
def blog_list(request):
    blogs = Blog.objects.filter(author=request.user).prefetch_related(Prefetch('sections', queryset=ContentSection.objects.order_by('order'))).all()
    return render(request, 'blog/list_blog.html', context={'blogs': blogs})

@login_required
def create_area_label(request, id):
    if request.method == "POST":
        province = request.POST.get('province')
        province = province.split('-')
        city = request.POST.get('city')
        city = city.split('-')

        blog = Blog.objects.get(id=id)

        if blog.author.username != request.user.username:
            return HttpResponse('You need to be the author to edit a blog')
        
        try:
            area = blog.blog_area_label.all().get(province=province[1], city=city[1])
            if area:
                message = "label existed"
        except Area.DoesNotExist:
            message = "label created"
            Area.objects.create(province=province[1], city=city[1], blog_labeled=blog)

        list_area_label = { area.id : str(area) for area in blog.blog_area_label.all()}

        dict_data_area = json.loads(json.dumps({'list_area_label' : [list_area_label], 'message':message}))
        
        return JsonResponse(dict_data_area, safe=False)    

@login_required
def delete_area_label(request, id, area_id):
    deleted, message = None, None
    blog = Blog.objects.get(id=id)
    area_label = blog.blog_area_label.all()

    if blog:
        if blog.author.username != request.user.username:
            return HttpResponse('You need to be the author to edit a blog')

        if area_label:
            deleted = area_label.get(id=area_id).delete()
            if deleted:
                message = "Label has been deleted!"
            else:
                message = "Fail deleting label, please try again!"

        else:
            message = "No label can be found!"
    else:
        message = "No blog can be found!"
    
    dict_delete_status = json.loads(json.dumps({'status_delete' : message}))

    return JsonResponse(dict_delete_status, safe=False)

@login_required
def create_activity_label(request, id):
    if request.method == "POST":
        activity = request.POST.get('activity')
        activity = activity.split('-')

        blog = Blog.objects.get(id=id)
        
        if blog.author.username != request.user.username:
            return HttpResponse('You need to be the author to edit a blog')

        try:
            act = blog.activity_labels.all().get(name=activity[1])    
            if act:
                message = "label existed"
        except ActivityLabel.DoesNotExist:
            message = "label created"
            act = ActivityLabel.objects.get(id=activity[0])
            blog.activity_labels.add(act)
            blog.save()

        list_act_label = { activity.id : activity.name for activity in blog.activity_labels.all()}

        dict_data_act = json.loads(json.dumps({'list_activity_label' : [list_act_label], 'message':message}))
        
    else:
        list_all_act_label = { activity.id : activity.name for activity in ActivityLabel.objects.all() }
    
        dict_data_act = json.loads(json.dumps({'list_all_act_label' : [list_all_act_label]}))

    return JsonResponse(dict_data_act, safe=False)

@login_required
def delete_activity_label(request, id, activity_id):
    message = None
    blog = Blog.objects.get(id=id)
    act_label = ActivityLabel.objects.get(id=activity_id)

    if blog:
        if blog.author.username != request.user.username:
            return HttpResponse('You need to be the author to edit a blog')
            
        if act_label:
            blog.activity_labels.remove(act_label)
            blog.save()
            
            try:
                blog.activity_labels.all().get(id=activity_id)   
            except ActivityLabel.DoesNotExist:
                message = "Label has been deleted!"
        
        else:
            message = "No label can be found!"
    else:
        message = "No blog can be found!"
    
    dict_delete_status = json.loads(json.dumps({'status_delete' : message}))  

    return JsonResponse(dict_delete_status, safe=False)

def detail(request, blog_id):
    blog = Blog.objects.filter(id=blog_id).prefetch_related(Prefetch('sections', queryset=ContentSection.objects.order_by('order'))).get()

    if blog != None and (blog.is_published or request.user.username == blog.author.username):
        all_comments = Comment.objects.all().order_by('-timestamp')
        comments = []
        for base_comment in all_comments:
            if base_comment.blog == blog and base_comment.replyTo == None:
                base_replies_pair = []
                base_replies_pair.append(base_comment)
                base_comment_replies = []
                for reply_comment in all_comments:
                    if reply_comment.replyTo == base_comment:
                        base_comment_replies.append(reply_comment)
                base_replies_pair.append(base_comment_replies)
                comments.append(base_replies_pair)

        context = {
            "blog": blog,
            "comments": comments
        }
        return render(request, 'blog/blog_detail.html', context)

    else:
        return HttpResponseNotFound('Page doesn`t exists')

def create_comment(request, blog_id):
    if request.is_ajax and request.method == "POST" and request.user.is_authenticated:
        blog = get_object_or_404(Blog, id = blog_id)
        commentator = request.user
        new_comment = Comment(content=request.POST.get('newCommentContent', None) , blog=blog, commentator=commentator)
        new_comment.save()
        return JsonResponse({'blog_id' : blog.id}, status = 201)

def reply_comment(request, comment_id):
    if request.is_ajax and request.method == "POST" and request.user.is_authenticated:
        base_comment = get_object_or_404(Comment, id = comment_id)
        base_comment_blog = base_comment.blog
        commentator = request.user
        new_comment = Comment(content=request.POST.get('newCommentContent', None) , blog=base_comment_blog, commentator=commentator, replyTo=base_comment)
        new_comment.save()
        return JsonResponse({'blog_id' : base_comment_blog.id}, status = 201)

def edit_comment(request, comment_id):
    if request.is_ajax and request.method == "PUT" and request.user.is_authenticated:
        comment = get_object_or_404(Comment, id = comment_id)
        comment_blog = comment.blog
        put = QueryDict(request.body)
        new_comment_content = put.get('newCommentContent')
        if(comment.content == new_comment_content):

blog/templates/blog/activity_label_modal.html
<!-- The Modal -->
<div id="myModal2" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="title-form">Manage Activity Label</h2>
            <span class="close-modal">&times;</span>
        </div>
        
        <div class="modal-body">
            <div class="view-container activity-selected">
                <p class="subtitle-view">Added Label</p>
                <div class="container-selected">
                    <ul class="list-label activity-selected" id="list-label activity-selected">
                        {% for ac in blog.activity_labels.all %}
                        <div class="item-container">
                            <li class="activity-items">
                                {{ ac.name }}
                            </li>
                            <a class="delete-item-label activity" href="{% url 'blog:delete_activity_label' blog.id ac.id %}">
                                <input class="delete-btn" type="button" value="&times;">
                            </a>
                        </div>
                        {% endfor %}
                    </ul>
                </div> 
            </div> 
            <div class="form-container activity-label">
                <form action="{% url 'blog:create_activity_label' blog.id %}" method="post" class="create-activity-label">
                    {% csrf_token %}
                    <div class="sub-form activity-input">
                        <p class="subtitle-form">Activity</p>
                        <select name="activity" id="activity-list" class="select-container item-activity">
                            <option value="-" disabled selected>-</option>
                        </select>
                    </div> 
                    <input class="submit-label activity-label" name="create-activity-label" type="submit" value="&plus;">
                </form>
            </div> 
            <a class="done-label" href="{% url 'blog:write' blog.id %}"><input class="save-label activity-label" type="button" value="Save Label"></a>
        </div>
        
    </div>
  
  </div>

blog/templates/blog/area_label_modal.html
<!-- The Modal -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="title-form">Manage Area Label</h2>
            <span class="close-modal">&times;</span>
        </div>
        
        <div class="modal-body">
            <div class="view-container area-selected">
                <p class="subtitle-view">Added Label</p>
                <div class="container-selected">
                    <ul class="list-label area-selected" id="list-label area-selected">
                        {% for ar in blog.blog_area_label.all %}
                        <div class="item-container">
                            <li class="area-items">
                                {{ ar.getLabel }}
                            </li>
                            <a class="delete-item-label area" href="{% url 'blog:delete_area_label' blog.id ar.id %}">
                                <input class="delete-btn" type="button" value="&times;">
                            </a>
                        </div>
                        {% endfor %}
                    </ul>
                </div> 
            </div> 
            <div class="form-container area-label">
                <form action="{% url 'blog:create_area_label' blog.id %}" method="post" class="create-area-label">
                    {% csrf_token %}
                    <div class="sub-form province-input">
                        <p class="subtitle-form">Province</p>
                        <select name="province" id="province-list" class="select-container item-province">
                            <option value="-" disabled selected>-</option>
                        </select>
                    </div> 

                    
                    <div class="sub-form city-input">
                        <p class="subtitle-form">City</p>
                        <select name="city" id="city-list" class="select-container item-city">
                            <option value="-" disabled selected>-</option>
                        </select>
                    </div>

                    <input class="submit-label area-label" name="create-area-label" type="submit" value="&plus;">
                </form>
            </div> 
            <a class="done-label" href="{% url 'blog:write' blog.id %}"><input class="save-label area-label" type="button" value="Save Label"></a>
        </div>
        
    </div>
  
  </div>

blog/templates/blog/blog_detail.html
{% extends 'base_navbar_no_search.html' %}

{% load static %}

{% block title %}Petualanganku{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/blog_detail/blog_detail.css' %}" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
{% endblock head %}

{% block body %}
<div id="detail-container">
    <div id="detail-blog">
        <div class="content-title">
                <p class="content-text content-text-title">{{ blog.title|safe }}</p>
        </div>
        <div class="content-profile">
            <img class="content-profile-image" src="{% static 'blog/blog_detail/images/kirito.jpg' %}" alt="Italian Trulli">
            <a class="content-profile-user" href="#">{{ blog.author.username }}</a>
            <div class="content-flex-filler"></div>
            <button class="content-header-button" id="report-modal-button" data-bs-toggle="modal" data-bs-target="#report-modal" >Report</button>

            {% if request.user.username == blog.author.username %}
            <a href="{% url 'blog:write' id=blog.id %}"">
                <button class="content-header-button" id="edit-button">Edit</button>
            </a>
            {% endif %}
        </div>

        {% for section in blog.sections.all %}
        {% if section.text_content != '' %}

        <div class="content-p">
            <p class="content-text content-text-p">{{ section.text_content|safe }}</p>
        </div>

        {% elif section.image_content != '' %}

        <div class="content-image">
            <img class="content-image-file" src="{{ section.image_content.url }}"/>

            {% if section.caption_content != '' %}
            <p class="content-text content-text-caption">{{ section.caption_content|safe }}</p>
            {% endif %}

        </div>

        {% endif %}
        {% endfor %}
    </div>
    <div id="comment-section">
        <div id="myModal" class="modal-comment">
            <div class="modal-content-comment">
                <div class="modal-body-comment">
                    <span class="close" onclick="closeModalPopUp()">&times;</span>
                    <p id="modalNotification"></p>
                </div>
            </div>
        </div>
        <div id="deleteModal" class="modal-comment">
            <div class="modal-content-comment">
                <div class="modal-header">
                    <h2>Are you sure want to delete this comment?</h2>
                </div>
                <div class="modal-body-comment" id="deleteModalBody">
                    <button type="button" id="sureDelete" onclick=" deleteComment()">Sure</button>
                    <p id="cancelDelete" onclick="closeModalPopUp()">Cancel</p>
                </div>
            </div>
        </div>
        <hr color= "#4AC0C0">
        <div id="comment-header">
            <div id="header-not-form">
                <h1>Comments</h1>
                {% if user.is_authenticated %}
                    <button type="button" onclick="showCreateForm('{{ blog.id }}')">Create comment</button>
                {% endif %}
            </div>
        </div>
        {% if comments %}
        <div id="comment-comment">
            {% for comment in comments %}
            <div class="a-comment">
                <div class="comment-top">
                    <div class = "top-image">
                        <img src="{% static 'blog/blog_detail/images/asuna.jpg' %}" alt="Profile picture pembuat komentar yang tidak sedang login">
                    </div>
                    <div class = "no-image-top">
                        <h4>{{ comment.0.commentator.username }}</h4>
                        <p>{{ comment.0.timestamp }}</p>
                    </div>
                </div>
                <div class="comment-body">
                    <p>{{ comment.0.content }}</p>
                </div>
                {% if user.is_authenticated %}
                <div class="comment-command">
                    {% if user.username == comment.0.commentator.username %}
                    <div class="left-command">
                        <p onclick="showEditForm(this, '{{ comment.0.id }}')">Edit</p>
                        <p onclick="showDeletePopup('{{ comment.0.id }}')">Delete</p>
                    </div>
                    <div class="right-command">
                        <p onclick='showReplyForm(this, "{{ comment.0.id }}")'>Reply</p>
                    </div>
                    {% else %}
                    <div class="just-right-comment-command">
                        <p onclick='showReplyForm(this, "{{ comment.0.id }}")'>Reply</p>
                    </div>
                    {% endif %}
                </div>
                {% endif %}
                {% for comment_replies in comment.1 %}
                <div class="reply-comment">
                    <div class="comment-top">
                        <div class = "top-image">
                            <img src="{% static 'blog/blog_detail/images/kirito.jpg' %}" alt="Profile picture pembuat komentar yang sedang login">
                        </div>
                        <div class = "no-image-top">
                            <h4>{{ comment_replies.commentator.username }}</h4>
                            <p>{{ comment_replies.timestamp }}</p>
                        </div>
                    </div>
                    <div class="comment-body">
                        <p>{{ comment_replies.content }}</p>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="comment-command">
                        {% if user.username == comment_replies.commentator.username %}
                        <div class="left-command">
                            <p onclick="showEditForm(this, '{{ comment_replies.id }}')">Edit</p>
                            <p onclick="showDeletePopup('{{ comment_replies.id }}')">Delete</p>
                        </div>
                        <div class="right-command">
                            <p onclick='showReplyForm(this, "{{ comment.0.id }}")'>Reply</p>
                        </div>
                        {% else %}
                        <div class="just-right-comment-command">
                            <p onclick='showReplyForm(this, "{{ comment.0.id }}")'>Reply</p>
                        </div>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    <!--Report Toast-->
    <div class="modal" id="report-modal" tabindex="-1">
        <div class="modal-dialog">
        <div class="modal-content ps-3 pe-3">
            <div class="modal-body">
            <h3>Report Blog</h3>
            </div>
            <form action="report/{{ blog.id }}" method="POST">
                {% csrf_token %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="report-type" value="Sexual content" checked>
                    <label class="form-check-label" for="report_type1">
                      Sexual content
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="report-type" value="Violent or repulsive content">
                    <label class="form-check-label" for="report_type2">
                      Violent or repulsive content
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="report-type" value="Hateful or abusive content">
                    <label class="form-check-label" for="report_type2">
                      Hateful or abusive content
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="report-type" value="Harmful or dangerous acts">
                    <label class="form-check-label" for="report_type2">
                      Harmful or dangerous acts
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="report-type" value="Spam or misleading">
                    <label class="form-check-label" for="report_type2">
                      Spam or misleading
                    </label>
                  </div>
                  <div class="form-floating">
                    <textarea name="report-description" class="form-control" placeholder="Leave a Description here" id="floatingTextarea" required></textarea>
                    <!-- <label for="floatingTextarea">Description</label> -->
                </div>

                <div class="modal-footer">
                    <input type="submit" value="Submit" class="btn" style="background-color: #4AA5A5;color: #FFFCF6;">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="{% static 'blog/blog_detail/blog_detail.js' %}"></script>
{% endblock script %}

blog/templates/blog/list_blog.html
{% extends 'base_navbar_no_search.html' %}

{% load static %}

{% block title %}My Blogs{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/blog_list/blog_list.css' %}" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock head %}

{% block body %}
<div id="list-container">
    <div class="header-container">
        <p class="header-title">Your Blogs</p>
        <a href="{% url 'blog:create' %}">
            <button class="header-write-button">Write Blog</button>
        </a>
    </div>
    <p class="header-subtitle">click on a blog to start editing</p>

    {% for blog in blogs %}

    <a href="{% url 'blog:write' id=blog.id %}">
        <div class="blog-container">
            <div class="blog-thumbnail-container">
                {% if blog.thumbnail != '' %}
                <img class="blog-thumbnail" src="{{ blog.thumbnail.url }}"/>
                {% else %}
                <p class="blog-thumbnail-placeholder">No Thumbnail</p>
                {% endif %}
            </div>
            <div class="blog-content-container">
                {% if blog.title != '' %}
                <p class="blog-title">{{ blog.title|safe }}</p>
                {% else %}
                <p class="blog-title">No Title Yet</p>
                {% endif %}

                <p class="blog-date blog-created">Created {{ blog.created|date:"l, j M y" }}</p>
                <p class="blog-date blog-updated">Last edited {{ blog.updated|date:"l, j M y" }}</p>

                {% if blog.is_published %}
                <p class="blog-status blog-published">Published</p>
                {% else %}
                <p class="blog-status blog-unpublished">Not Published</p>
                {% endif %}
            </div>
        </div>
    </a>

    {% endfor %}

</div>
{% endblock body %}

{% block script %}
<script src="{% static 'blog/blog_list/blog_list.js' %}"></script>
{% endblock script %}