authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # Blog creation
    path('create/', views.create, name='create'),
    path('write/<int:id>', views.write, name='write'),

    # Blog labeling
    path('write/<int:id>/create-area-label', views.create_area_label, name='create_area_label'),
    path('write/<int:id>/delete-area-label/<int:area_id>', views.delete_area_label, name='delete_area_label'),
    path('write/<int:id>/create-activity-label', views.create_activity_label, name='create_activity_label'),
    path('write/<int:id>/delete-activity-label/<int:activity_id>', views.delete_activity_label, name='delete_activity_label'),

    # Blog content editing
    path('section/delete/<int:section_id>', views.delete_blog_section, name='delete_section'),
    path('publish/<int:blog_id>', views.publish_blog, name='publish_blog'),
    path('unpublish/<int:blog_id>', views.unpublish_blog, name='unpublish_blog'),

    # Blog read
    path('<int:blog_id>', views.detail, name='detail_blog'),
    path('list/', views.blog_list, name='blog_list'),

    # Blog comments
    path('create-comment/<int:blog_id>', views.create_comment),
    path('reply-comment/<int:comment_id>', views.reply_comment),
    path('edit-comment/<int:comment_id>', views.edit_comment),
    path('delete-comment/<int:comment_id>', views.delete_comment),

    # Blog reports
    path('report/<int:blog_id>', views.report)
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about-us', views.about, name='about'),
    path('filter-search', views.filter_search, name='filter_search'),
    path('search-result', views.search_result, name='search_result')
]

labels/urls.py
from django.urls import path
from . import views
app_name = 'labels'

urlpatterns = [
    path('', views.manage, name='manage'),
    path('add/', views.add, name='add'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
]

manage_report/urls.py
from django.urls import path

from . import views

app_name = 'manage_report'

urlpatterns = [
    path('', views.reports, name='reports'),
    path('report-detail/<int:report_id>', views.report_detail, name = 'report_detail'),
    path('report-detail/accepted-form/<int:report_id>', views.accepted_form, name = 'accepted_form_report'),
    path('reject-report/<int:report_id>', views.reject_report, name = 'reject_report'),
    path('accept-report/<int:report_id>', views.accept_report,  name = 'accept_report'),
]

petualanganku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('blog/', include('blog.urls')),
    path('labels/', include('labels.urls')),
    path('', include('home.urls')),
    path('manage-report/', include('manage_report.urls')),
]

templates/base.html
<!DOCTYPE html>
<html>

{% load static %}

    <head>
        <title>{% block title %}{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

        <style>
            {% block styling %}
            {% endblock styling %}
        </style>
        
        {% block head %}
        {% endblock head %}
    </head>

    <body id="body" style="padding: 0; margin: 0;">
        
        {% block body %}
        {% endblock body %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="{% static 'script/script.js' %}"></script>

        {% block script %}
        {% endblock script %}
    </body>
</html>

templates/base_navbar.html
<!DOCTYPE html>
<html>

{% load static %}

    <head>
        <title>{% block title %}{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

        <style>
            {% block styling %}
            {% endblock styling %}
        </style>
        
        {% block head %}
        {% endblock head %}
    </head>

    <body id="body" style="padding: 0; margin: 0;">
        
        {% include 'navbar.html' %}

        {% block body %}
        {% endblock body %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="{% static 'script/script.js' %}"></script>

        {% block script %}
        {% endblock script %}
    </body>
</html>

templates/base_navbar_no_search.html
<!DOCTYPE html>
<html>

{% load static %}

    <head>
        <title>{% block title %}{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'navbar.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

        <style>
            {% block styling %}
            {% endblock styling %}
        </style>
        
        {% block head %}
        {% endblock head %}
    </head>

    <body id="body" style="padding: 0; margin: 0;">
        
        {% include 'navbar_no_search.html' %}

        {% block body %}
        {% endblock body %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="{% static 'script/script.js' %}"></script>

        {% block script %}
        {% endblock script %}
    </body>
</html>

templates/navbar.html
{% load static %}
<body id='nav-custom'>
    <div class="nav-container">
        <div class="nav-logo">
          <a href="{% url 'home:home' %}"><img class="main" src="{% static 'img/Logo Petualangku.svg' %}" alt="Petualangku's logo"></a>
        </div>
        <div class="nav-right-bar">
            <p class="nav-item-right about-menu"><a href="{% url 'home:about' %}">About Us</a></p>
            {# TODO: implement this to user.profile.is_admin #}
            {% if user.profile.is_admin %}
            <div class="nav-item-right nav-profile-dropdown my-profile-menu" style="margin-right: 0.1rem;">
                <div class="nav-dropdown-text">
                    <p>Manage</p>
                    <div style="width: 0.5rem;"></div>
                    <i class="nav-dropdown-arrow"></i>
                </div>
                <ul class="nav-profile-dropdown-menu">
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'labels:manage' %}">Manage Labels</a></li>
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'manage_report:reports' %}">Manage Reports</a></li>
                </ul>
            </div>
            {% endif %}
            <div class="nav-item-right nav-profile-dropdown my-profile-menu" style="margin-right: 4rem;">
                <div class="nav-dropdown-text">
                    <p>My Profile</p>
                    <div style="width: 0.5rem;"></div>
                    <i class="nav-dropdown-arrow"></i>
                </div>
                <ul class="nav-profile-dropdown-menu">
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="#">Settings</a></li>
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'blog:blog_list' %}">My Blogs</a></li>
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'blog:create' %}">Write Blog</a></li>
                    <li><hr class="nav-dropdown-divider"></li>
                    {% if user.is_authenticated %}
                        <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'authentication:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'authentication:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="input-group nav-search">
              <form action="{% url 'home:search_result' %}" method="post" class="form-search">
                {% csrf_token %}
                <input type="text" class="form-control custom-search-bar" name="keyword-search" aria-label="Text input with segmented dropdown button" placeholder="Search blog here..." required>
                <button type="submit" class="btn btn-custom submit-search">Search</button>
              </form>
              <button type="button" class="btn btn-custom dropdown-toggle dropdown-toggle-split sub-search" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu dropdown-menu-end" id="dropdown-custom">
                <li><a class="dropdown-item" href="{% url 'home:filter_search' %}">Filtered search</a></li>
              </ul>
            </div>
        </div>
    </div> 
</body>

templates/navbar_no_search.html
{% load static %}
<div class="nav-container">
    <div class="nav-logo">
        <a href="{% url 'home:home' %}"><img class="main" src="{% static 'img/Logo Petualangku.svg' %}" alt="Petualangku's logo"></a>
    </div>
    <div class="nav-right-bar">
        <p class="nav-item-right about-menu"><a href="{% url 'home:about' %}">About Us</a></p>
        <div class="nav-item-right nav-profile-dropdown my-profile-menu">
            <div class="nav-dropdown-text">
                <p>My Profile</p>
                <div style="width: 0.5rem;"></div>
                <i class="nav-dropdown-arrow"></i>
            </div>
            <ul class="nav-profile-dropdown-menu" style="top: 0.1rem;">
                <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="#">Settings</a></li>
                <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'blog:blog_list' %}">My Blogs</a></li>
                <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'blog:create' %}">Write Blog</a></li>
                <li><hr class="nav-dropdown-divider"></li>
                {% if user.is_authenticated %}
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'authentication:logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-dropdown-item-container"><a class="nav-dropdown-item" href="{% url 'authentication:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>